### PR TITLE
Library expansion

### PR DESCRIPTION
**Pull request by garyb**
@paf31 so, something like this? Events is probably the worst case.

Not for merging yet.

### CODE REVIEW

**Comment by paf31** [comment]
Certainly looks nice and straightforward :+1:

**Comment by garyb** [comment]
Bump for a re-review. This is now good enough to support Halogen, but I lost the will to live when going through all the IDLs and adding every method for all the different APIs, so the major types are here, a bunch of useful functions etc, and it will just have to grow over time from this point ;) I think it should be doable in a way that it won't require a major version bump.

I need to re-add the File/XHR stuff for Affjax still however.

**Comment by garyb** [comment]
Oh wait, I need to push first.

**Comment by garyb** [comment]
There we go...

**Comment by paf31** [comment]
Wow, you've been busy :)

**Comment by garyb** [comment]
I though "nyeh, how long can it take?" and then once I finished with 90% of the DOM specification I realised I also needed to go through the HTML5 specification (for HTMLDocument, HTMLElement, etc) and then Browser too (Window). That was the point I started to lose interest and just implement the stuff Halogen needed :wink:

**Comment by jdegoes** [comment]
Too late but :+1: :smile:

**Pull request merged**
