### PR TITLE
Update for 0.10.

### PR DESCRIPTION
**Pull request by bodil**

### CODE REVIEW

**Comment by jutaro** [comment]
Can you please pull, I need this too!

**Comment by garyb** [comment]
I'll get this done today - there's a few other PRs that need merging too. Thanks @bodil!

**Comment by garyb** [comment]
@bodil @jutaro Now released as v3.0.0 - sorry for the delay!

**Comment by jutaro** [comment]
Cool, thanks

2016-10-20 16:12 GMT+02:00 Gary Burgess <notifications@github.com>:

**Pull request merged**
