### PR TITLE
Fix warnings generated by purescript 0.8.0

### PR DESCRIPTION
**Pull request by telser**

### CODE REVIEW

**Comment by AlexMouton** [comment]
This is not my domain but I'd like to see this go in.
60+ warnings to use this package is a pain.

**Comment by garyb** [comment]
Yeah, I hear that! SlamData currently generates over 2k warnings when we compile it...

We're working on getting the core libraries updated and out there first though, as otherwise we'll have to do another round of breaking changes to libraries like this once core is updated.

**Comment by nwolverson** [comment]
This PR looks to be defunct - library is now 0 warnings in 0.9

**Comment by garyb** [comment]
Thanks for the reminder!

**Pull request closed without merging**
