### PR TITLE
Functionality to create FormData objects.

### PR DESCRIPTION
**Pull request by jprider63**
Moving ability to create FormData objects here as per slamdata/purescript-affjax#57.

### CODE REVIEW

**Comment by garyb** [comment]
Thanks!

We could probably do a little internal cheating here to avoid the need to implement `append` with all of its various types in the FFI:

1. We could have an unexported `foreign import data FormDataBox :: *`
2. and unexported `foreign import appendImpl :: FormData -> String -> FormDataBox -> String -> Unit`
3. and then use `appendImpl` for any of the acceptable values, using `unsafeCoerce` to go from `Blob`, `String`, etc. to `FormDataBox`.

Or even just type `appendImpl` as `forall a. FormData -> String -> a -> String -> Unit` perhaps.

I'd also like to suggest we provide `fromFoldable :: forall f. (Foldable f) => f (Tuple String FormDataValue) -> FormData` instead of having `toFormData` specialised to `Array`, as that way it will also work for `List`, etc.

**Comment by garyb** [comment]
Oh, whoops, I just noticed that the appends are not all equivalent in their arguments. In that case, perhaps there's an `appendWithName` or something to handle the Blob/File case, with the above suggestion to avoid having to implement multiply.

**Comment by jprider63** [comment]
No problem! I think my last commit should address your suggestions. Let me know if you think of anything else.

**Comment by garyb** [comment]
That was fast :smile:

Thanks again! Sorry it took so long to get to this point from your initial PR.

**Pull request merged**
