### PR TITLE
Updates for 0.11

### PR DESCRIPTION
**Pull request by paf31**
I couldn't update the tests because of the test dependencies. Also, I just deleted the `IsForeign` instances, not sure if you wanted to do that or something else.

### CODE REVIEW

**Comment by garyb** [comment]
Thanks! I'll probably disable the tests for a release and reinstate them when the updates are done.

Going to update the FFI stuff to use the uncurried things now too!

**Comment by garyb** [comment]
Actually I'm not updating the FFI just now, that's crazy talk. It'll take quite a while to do, and until we get fancy with the optimizer for `EffFn` it's not really very interesting anyway.

**Comment by paf31** [comment]
So shall we release this as it is then?

**Comment by garyb** [comment]
Will do in a moment, #88 :)

**Pull request merged**
