### PR TITLE
add innerHTML and setInnerHTML

### PR DESCRIPTION
**Pull request by sharkdp**
Add support for [Element.innerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML)

### CODE REVIEW

**Comment by garyb** [comment]
Interesting, it appears this isn't strictly speaking part of the [DOM](http://www.w3.org/TR/dom/) or [HTML 5](http://www.w3.org/TR/html5/) specs, although it is listed in this "living standard" https://w3c.github.io/DOM-Parsing/#widl-Element-innerHTML

I think it should probably belong to `HTMLElement` rather than `Element` however, as the DOM Node interface also represents XML nodes (SVG, etc.) where `innerHTML` would not apply.

**Comment by sharkdp** [comment]
Oops, it didn't come to my mind that `innerHTML` would not be part of the spec. It is a rather 'unsafe' function and usually there are better ways to achieve the same result. So I'm actually also fine with canceling this PR, if you want.

If you want to keep it, I believe it should belong to `Element`. Despite it's name, it should work just as well for XML (SVG) documents (see the 'living standard' document that you referred to). It's part of "Extensions to the Element interface".

**Comment by garyb** [comment]
I'm not sure what to do here. `innerHTML` is definitely a bit evil, but it's probably also really useful... maybe we could omit it for now, and if there is enough demand, add it in.

**Comment by sharkdp** [comment]
Okay, so I'll just leave this open as is..

**Pull request closed without merging**
