### PR TITLE
(WIP) Updates for compiler 0.12

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Haven't updated tests yet because not all the test dependencies are up to date.

### CODE REVIEW

**Comment by garyb** [comment]
Noo, sorry you did all this - this library is going to die! (Previously: #150)

**Comment by garyb** [comment]
(I'm mostly done with releasing the new ones, just finishing up the last few now)

**Comment by LiamGoodacre** [comment]
Don't worry I did it all with sed scripts aha, didn't waste any time really.

**Comment by garyb** [comment]
Still, sorry!

I've moved this to `purescript-deprecated` to hopefully avoid anyone else spending time on it - will add a notice explaining the situation fully once I've finished with the new releases.

**Comment by LiamGoodacre** [comment]
Excellent, thanks!

**Pull request closed without merging**
